name: nutrilink
description: "Recommender System for Dynamic Meal Scheduling and Caloric Intake Management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_app_check: ^0.3.2+10
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.5.0
  fl_chart: ^1.1.1
  geolocator: ^14.0.2        # Add Geolocator
  geocoding: ^4.0.0
  firebase_storage: ^12.4.10
  cached_network_image: ^3.4.1
  google_generative_ai: ^0.4.7  # Gemini AI API (latest available)
  shared_preferences: ^2.5.3

  # UI helper
  flutter_cupertino_datetime_picker: ^3.0.0

  # File picker / image picker (buat upload ke Storage)
  image_picker: ^1.1.2        # <── TAMBAHAN: ambil foto/galeri di mobile
  # file_picker: ^8.0.0       # (opsional kalau mau support web/other files)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo NutriLink.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/Logo NutriLink.png"
    background_color: "#FFFFFF"   # ganti dari "#hexcode"
    theme_color: "#5F9C3F"        # misal hijau NutriLink
  windows:
    generate: true
    image_path: "assets/images/Logo NutriLink.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/Data Privacy Illustration.png
    - assets/images/Login Illustration.png
    - assets/images/Logo Google.png
    - assets/images/Logo HealthyGo.png
    - assets/images/Logo NutriLink.png
    - assets/images/Male Avatar.png
    - assets/images/Female Avatar.png
    - assets/images/Seafood.png
    - assets/images/
    - assets/images/Fish.png
    - assets/images/Shrimp.png
    - assets/images/Beef.png
    - assets/images/Chicken.png

  fonts:
    - family: Funnel Display
      fonts:
        - asset: assets/fonts/FunnelDisplay.ttf
